name: Issue
description: Report a bug, request a feature, or ask a question
labels: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug
        - Feature Request
        - Question
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue, feature, or question
      placeholder: What's happening? What would you like to see? What do you need help with?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information, code examples, or screenshots
      placeholder: |
        - Steps to reproduce (for bugs)
        - Use case (for features)
        - Related issues or PRs
    validations:
      required: false
